[package]
name = "rustchain"
version = "0.1.0"
authors = ["Jake <jake.trefethen@gmail.com>"]

[dependencies]
sha2 = "0.7"
iron = "0.5.1"
mime = "0.2.3"
router = "0.5.1"
urlencoded = "0.5.0"
uuid = { version = "0.6", features = ["v4"] }
